version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    ports:
      - 3000:3000