version: '3'

services:
  app:
    container_name: prod-app
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    