import StyleRegistry from "@/components/StyleRegistry";
import "tailwindcss/tailwind.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyleRegistry>{children}</StyleRegistry>
      </body>
    </html>
  );
}
